# Generated by Django 2.2.25 on 2022-06-13 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructures',
            fields=[
                ('nom', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=15)),
                ('machine', models.SmallIntegerField()),
                ('personnel', models.CharField(max_length=15)),
                ('responsable', models.CharField(max_length=15)),
                ('date_de_maintenance', models.DateField(default=datetime.datetime(2022, 6, 13, 7, 48, 53, 353464))),
            ],
        ),
    ]
