# Generated by Django 2.2.25 on 2022-06-13 08:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0003_auto_20220613_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_personnel', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_machine', models.SmallIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='infrastructures',
            old_name='machine',
            new_name='list_machine',
        ),
        migrations.RemoveField(
            model_name='infrastructures',
            name='personnel',
        ),
        migrations.AlterField(
            model_name='infrastructures',
            name='date_de_maintenance',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 8, 11, 46, 975103)),
        ),
        migrations.AlterField(
            model_name='infrastructures',
            name='position',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='infrastructures',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnels.Personnel'),
        ),
        migrations.AddField(
            model_name='infrastructures',
            name='List_machine',
            field=models.ManyToManyField(to='infrastructures.Tag2'),
        ),
        migrations.AddField(
            model_name='infrastructures',
            name='List_personnel',
            field=models.ManyToManyField(to='infrastructures.Tag1'),
        ),
    ]
