# Generated by Django 2.2.25 on 2022-06-13 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0004_auto_20220613_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructures',
            name='list_machine',
        ),
        migrations.AlterField(
            model_name='infrastructures',
            name='date_de_maintenance',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 8, 13, 25, 856577)),
        ),
    ]
