# Generated by Django 2.2.25 on 2022-06-13 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0009_auto_20220613_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructures',
            name='date_de_maintenance',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 9, 3, 1, 308023)),
        ),
    ]
