# Generated by Django 2.2.25 on 2022-06-13 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0020_auto_20220613_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructures',
            name='date_de_maintenance',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 13, 0, 49, 351860)),
        ),
    ]
