# Generated by Django 2.2.25 on 2022-04-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('secu', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=15)),
                ('Prenom', models.CharField(max_length=15)),
            ],
        ),
    ]
