# Generated by Django 2.2.25 on 2022-05-03 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0002_personnel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='Prenom',
            new_name='prenom',
        ),
        migrations.AddField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('PC', 'PC - Run windows'), ('Mac', 'MAc - Run MacOS'), ('Serveur', 'Serveur - Simple Server to deploy virtual machines'), ('Switch', 'Switch - To maintains and connect servers ')], default='PC', max_length=32),
        ),
        migrations.AddField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 3, 9, 8, 54, 865555)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='secu',
            field=models.BigIntegerField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
