# Generated by Django 2.2.25 on 2022-05-03 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0003_auto_20220503_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 3, 9, 11, 15, 962371)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='secu',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
