# Generated by Django 2.2.25 on 2022-05-03 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0004_auto_20220503_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 3, 9, 24, 12, 925427)),
        ),
    ]
