# Generated by Django 2.2.25 on 2022-05-24 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0006_auto_20220503_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 7, 24, 41, 744260)),
        ),
    ]
