# Generated by Django 2.2.25 on 2022-05-30 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0010_auto_20220524_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 30, 9, 49, 8, 552572)),
        ),
    ]
