# Generated by Django 2.2.25 on 2022-06-11 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0011_auto_20220530_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 11, 13, 26, 190925)),
        ),
    ]
