# Generated by Django 2.2.25 on 2022-06-12 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0026_auto_20220612_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 12, 16, 52, 11, 939376)),
        ),
    ]
