# Generated by Django 2.2.25 on 2022-06-12 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0030_auto_20220612_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 12, 21, 8, 53, 93980)),
        ),
    ]
