# Generated by Django 2.2.25 on 2022-06-13 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0032_auto_20220613_0748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
