# Generated by Django 2.2.25 on 2022-06-13 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('secu', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=15)),
                ('machine_perso', models.SmallIntegerField()),
                ('lieu_travail', models.CharField(max_length=15)),
                ('date_de_maintenance', models.DateField(default=datetime.datetime(2022, 6, 13, 7, 48, 53, 351663))),
            ],
        ),
    ]
