# Generated by Django 2.2.25 on 2022-06-13 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0005_auto_20220613_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='date_de_maintenance',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 8, 13, 30, 799564)),
        ),
    ]
