# Generated by Django 2.2.25 on 2022-06-13 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0017_auto_20220613_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='date_de_maintenance',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 11, 41, 23, 460286)),
        ),
    ]
