# Generated by Django 2.2.25 on 2022-06-13 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('proprietaire', models.CharField(max_length=6)),
                ('infra', models.CharField(max_length=6)),
                ('maintenanceDate', models.DateField(default=datetime.datetime(2022, 6, 13, 7, 48, 53, 352982))),
            ],
        ),
    ]
