# Generated by Django 2.2.25 on 2022-06-13 07:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20220613_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='infra',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 7, 57, 5, 909454)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='proprietaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnels.Personnel'),
        ),
    ]
